### ISSUE TITLE
Support manual authentication

### ISSUE THREAD

**Issue by msafi** [orange-org/orange#19]
Currently Orange [looks for the `datadir` at the default location to find `bitcoin.conf`](https://github.com/orange-org/orange/blob/master/src/main/getRpcCredentials.ts). This tells it whether the full node is using `mainnet`, `testnet` or `regtest`. Based on that, it finds the `.cookie` file and uses it to authenticate.

According to this [reddit comment](https://www.reddit.com/r/Bitcoin/comments/fw0s9n/first_beta_release_of_orange_a_blockchain/fmmh5zs?utm_source=share&utm_medium=web2x) dedicated full nodes are more likely to be running on a different machine than the user's desktop computer.

In that case, the user would have to enter the RPC credentials manually. 

There are a few other things to consider in this case:

* Latency: Orange UI experience is not designed to expect slow-latency RPC calls. For example, it doesn't show loading indicators for most calls. This will need to be improved if most calls have slower latency.
* Full node URL: the URL `http://localhost` is currently hardcoded. Would we need to make this configurable as well?

**Comment by mmgen** [comment]
To determine the node's chain, use the RPC call `getblockchaininfo`. Parsing `bitcoin.conf` won't work if the chain has been selected on the command line.  This goes for other config options as well.

Have a configuration file where the user's RPC credentials are stored, so they don't have to be entered each time the explorer is run.

Of course, the node's host should be configurable as well.

If the node is synced, the latency of cheap RPC calls like `getblockchaininfo` will be unnoticeable for most users.

**Comment by msafi** [comment]
>To determine the node's chain, use the RPC call `getblockchaininfo`.

My understanding is that to make the RPC call `getblockchaininfo`, Orange would need to authenticate. To authenticate, it would need to find `.cookie`, which can be in any one of three locations, `datadir/`, `datadir/testnet3`, or `datadir/regtest`. To determine the correct location, it has to parse `bitcoin.conf`.

But thanks for bringing my attention to the fact that configs could be changed from the command line. I should keep that in mind for the code.

And thanks for clearing up the other questions. I'll look into supporting this use-case.

**Comment by mmgen** [comment]
> My understanding is that to make the RPC call `getblockchaininfo`, Orange would need to authenticate. To authenticate, it would need to find `.cookie`, which can be in any one of three locations, `datadir/`, `datadir/testnet3`, or `datadir/regtest`. To determine the correct location, it has to parse `bitcoin.conf`.

To authenticate, the client (Orange in this case) only needs to provide the correct credentials to the server (Bitcoin Core in this case). Where the credentials come from is unimportant. It could get them a) from the files `.cookie` or `bitcoin.conf` (as you're currently doing), b)  by prompting the user for them, or c) from its own configuration file. If the server is on a remote host, option A would require copying files from the remote host and is therefore impractical. This leaves you realistically with options B or C for non-local nodes.

The user sets their credentials on the remote node using either `rpcuser:rpcpassword` or `rpcauth`.  This can be done either in the node's `bitcoin.conf` or on its command line. Then Orange is configured with these same credentials using options B or C.

**Comment by msafi** [comment]
This release supports manual authentication as we discussed if you wanna give it a try https://github.com/orange-org/orange/releases/tag/1.0.0-beta.4
